# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "C:/Users/Jared Woolston/Documents/GitHub/serv-hardware/servant_1.3.0/zcu106-vivado/.Xil/Vivado-128224-DESKTOP-8CFAEH8/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    rt::set_parameter datapathDensePacking false
    set rt::partid xczu7ev-ffvc1156-2-e
    source $::env(HRT_TCL_PATH)/rtSynthParallelPrep.tcl
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common.tcl
    set rt::defaultWorkLibName xil_defaultlib
    rt::set_parameter defaultVhdlWorkLib xil_defaultlib

    rt::set_parameter loadVhdl2008Libs false
    rt::set_parameter loadVhdl2019Libs false
    rt::set_parameter deferParseUntilElab true
    rt::set_parameter sortHdlCommandLine true
    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog -include {{C:/Users/Jared Woolston/Documents/GitHub/serv-hardware/servant_1.3.0/zcu106-vivado}} {
      {C:/Users/Jared Woolston/Documents/GitHub/serv-hardware/servant_1.3.0/zcu106-vivado/src/serv_1.3.0/rtl/serv_bufreg.v}
      {C:/Users/Jared Woolston/Documents/GitHub/serv-hardware/servant_1.3.0/zcu106-vivado/src/serv_1.3.0/rtl/serv_bufreg2.v}
      {C:/Users/Jared Woolston/Documents/GitHub/serv-hardware/servant_1.3.0/zcu106-vivado/src/serv_1.3.0/rtl/serv_alu.v}
      {C:/Users/Jared Woolston/Documents/GitHub/serv-hardware/servant_1.3.0/zcu106-vivado/src/serv_1.3.0/rtl/serv_csr.v}
      {C:/Users/Jared Woolston/Documents/GitHub/serv-hardware/servant_1.3.0/zcu106-vivado/src/serv_1.3.0/rtl/serv_ctrl.v}
      {C:/Users/Jared Woolston/Documents/GitHub/serv-hardware/servant_1.3.0/zcu106-vivado/src/serv_1.3.0/rtl/serv_decode.v}
      {C:/Users/Jared Woolston/Documents/GitHub/serv-hardware/servant_1.3.0/zcu106-vivado/src/serv_1.3.0/rtl/serv_immdec.v}
      {C:/Users/Jared Woolston/Documents/GitHub/serv-hardware/servant_1.3.0/zcu106-vivado/src/serv_1.3.0/rtl/serv_mem_if.v}
      {C:/Users/Jared Woolston/Documents/GitHub/serv-hardware/servant_1.3.0/zcu106-vivado/src/serv_1.3.0/rtl/serv_rf_if.v}
      {C:/Users/Jared Woolston/Documents/GitHub/serv-hardware/servant_1.3.0/zcu106-vivado/src/serv_1.3.0/rtl/serv_rf_ram_if.v}
      {C:/Users/Jared Woolston/Documents/GitHub/serv-hardware/servant_1.3.0/zcu106-vivado/src/serv_1.3.0/rtl/serv_rf_ram.v}
      {C:/Users/Jared Woolston/Documents/GitHub/serv-hardware/servant_1.3.0/zcu106-vivado/src/serv_1.3.0/rtl/serv_state.v}
      {C:/Users/Jared Woolston/Documents/GitHub/serv-hardware/servant_1.3.0/zcu106-vivado/src/serv_1.3.0/rtl/serv_top.v}
      {C:/Users/Jared Woolston/Documents/GitHub/serv-hardware/servant_1.3.0/zcu106-vivado/src/serv_1.3.0/rtl/serv_rf_top.v}
      {C:/Users/Jared Woolston/Documents/GitHub/serv-hardware/servant_1.3.0/zcu106-vivado/src/serv_1.3.0/rtl/serv_aligner.v}
      {C:/Users/Jared Woolston/Documents/GitHub/serv-hardware/servant_1.3.0/zcu106-vivado/src/serv_1.3.0/rtl/serv_compdec.v}
      {C:/Users/Jared Woolston/Documents/GitHub/serv-hardware/servant_1.3.0/zcu106-vivado/src/servile_1.3.0/servile/servile_rf_mem_if.v}
      {C:/Users/Jared Woolston/Documents/GitHub/serv-hardware/servant_1.3.0/zcu106-vivado/src/servile_1.3.0/servile/servile_mux.v}
      {C:/Users/Jared Woolston/Documents/GitHub/serv-hardware/servant_1.3.0/zcu106-vivado/src/servile_1.3.0/servile/servile_arbiter.v}
      {C:/Users/Jared Woolston/Documents/GitHub/serv-hardware/servant_1.3.0/zcu106-vivado/src/servile_1.3.0/servile/servile.v}
      {C:/Users/Jared Woolston/Documents/GitHub/serv-hardware/servant_1.3.0/zcu106-vivado/src/servant_1.3.0/servant/servant_timer.v}
      {C:/Users/Jared Woolston/Documents/GitHub/serv-hardware/servant_1.3.0/zcu106-vivado/src/servant_1.3.0/servant/servant_gpio.v}
      {C:/Users/Jared Woolston/Documents/GitHub/serv-hardware/servant_1.3.0/zcu106-vivado/src/servant_1.3.0/servant/servant_mux.v}
      {C:/Users/Jared Woolston/Documents/GitHub/serv-hardware/servant_1.3.0/zcu106-vivado/src/servant_1.3.0/servant/servant_ram.v}
      {C:/Users/Jared Woolston/Documents/GitHub/serv-hardware/servant_1.3.0/zcu106-vivado/src/servant_1.3.0/servant/servant.v}
      {C:/Users/Jared Woolston/Documents/GitHub/serv-hardware/servant_1.3.0/zcu106-vivado/src/servant_1.3.0/servant/servus_clock_gen.v}
      {C:/Users/Jared Woolston/Documents/GitHub/serv-hardware/servant_1.3.0/zcu106-vivado/src/servant_1.3.0/servant/servus.v}
    }
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top servus
    rt::set_parameter enableIncremental true
    rt::set_parameter markDebugPreservationLevel "enable"
    set rt::reportTiming false
    rt::set_parameter lint_verbosity true
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter dataflowBusHighlighting false
    rt::set_parameter generateDataflowBusNetlist false
    rt::set_parameter dataFlowViewInElab false
    rt::set_parameter busViewFixBrokenConnections false
    rt::set_parameter elaborateRtlOnlyFlow true
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter synthDebugLog false
    rt::set_parameter printModuleName false
    rt::set_parameter enableSplitFlowPath "C:/Users/Jared Woolston/Documents/GitHub/serv-hardware/servant_1.3.0/zcu106-vivado/.Xil/Vivado-128224-DESKTOP-8CFAEH8/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_rtlelab -param {{ memsize 8192 }} -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
